#!/usr/bin/env python
"""
example code for setting integration src_code, environment, secrets via public_api

Copyright (C) 2020 Cogniac Corporation
"""
import cogniac
import sys
from time import time

t0 = time()

# read requirements.txt
try:
    requirements = open('requirements.txt').read()
except:
    requirements = None

src_fn = "integration.py"

src_config = {'name': 'foo-bar',
              'description': 'test code',
              'requirements': requirements,
              'src_code': open(src_fn).read()}


cc = cogniac.CogniacConnection()


#res = cc._get('/builds/version')
#print res.content

try:
    res = cc._post("/builds", json=src_config)
except cogniac.ClientError as e:
    print e.message
    sys.exit(1)
except cogniac.ServerError as e:
    print e.message
    sys.exit(2)

build = res.json()
print build['image']

print "\nElapsed time: %.1f seconds" % (time() - t0)
print


"""
cc._get("/builds/%s" % build['build_id'])
cc._delete("/builds/%s" % build['build_id'])

url = "/builds?name=foo-bar&limit=17&reverse=True"
while True:
    res = cc._get(url).json()
    for i in res['data']:
        print "%s %3d  %f"  % (i['name'], i['version'], i['created_at'])
    if 'next' in res['paging']:
        url = res['paging']['next']
        print url
    else:
        break
"""
